va = input("Crie uma variavel:")
print('O tipo dessa variavel é', type(va))
print('Só tem espaços?', va.isspace())
print('é alfabética?', va.isalpha())
print('é numérica?', va.isnumeric())
print('possui letras e números?', va.isalnum())
print('esta tudo em minúsculo?', va.islower())
print('esta tudo em maiúsculo?', va.isupper())
print('tem letras maiúsculas e minúsculas?', va.istitle())
